package brs.http.common

object Parameters {

    val ALIAS_PARAMETER = "alias"
    val AMOUNT_NQT_PARAMETER = "amountNQT"
    val ALIAS_NAME_PARAMETER = "aliasName"
    val FEE_NQT_PARAMETER = "feeNQT"
    val PRICE_NQT_PARAMETER = "priceNQT"
    val QUANTITY_QNT_PARAMETER = "quantityQNT"
    val ASSET_PARAMETER = "asset"
    val ASSETS_PARAMETER = "assets"
    val GOODS_PARAMETER = "goods"
    val ORDER_PARAMETER = "order"
    val QUANTITY_PARAMETER = "quantity"
    val ENCRYPTED_MESSAGE_DATA_PARAMETER = "encryptedMessageData"
    val ENCRYPTED_MESSAGE_NONCE_PARAMETER = "encryptedMessageNonce"
    val MESSAGE_TO_ENCRYPT_PARAMETER = "messageToEncrypt"
    val MESSAGE_TO_ENCRYPT_IS_TEXT_PARAMETER = "messageToEncryptIsText"
    val ENCRYPT_TO_SELF_MESSAGE_DATA = "encryptToSelfMessageData"
    val ENCRYPT_TO_SELF_MESSAGE_NONCE = "encryptToSelfMessageNonce"
    val MESSAGE_TO_ENCRYPT_TO_SELF_PARAMETER = "messageToEncryptToSelf"
    val MESSAGE_TO_ENCRYPT_TO_SELF_IS_TEXT_PARAMETER = "messageToEncryptToSelfIsText"
    val GOODS_DATA_PARAMETER = "goodsData"
    val GOODS_NONCE_PARAMETER = "goodsNonce"
    val PURCHASE_PARAMETER = "purchase"
    val SECRET_PHRASE_PARAMETER = "secretPhrase"
    val PUBLIC_KEY_PARAMETER = "publicKey"
    val ACCOUNT_PARAMETER = "account"
    val TIMESTAMP_PARAMETER = "timestamp"
    val RECIPIENT_PARAMETER = "recipient"
    val RECIPIENTS_PARAMETER = "recipients"
    val SELLER_PARAMETER = "seller"
    val BUYER_PARAMETER = "buyer"
    val FIRST_INDEX_PARAMETER = "firstIndex"
    val LAST_INDEX_PARAMETER = "lastIndex"
    val NUMBER_OF_CONFIRMATIONS_PARAMETER = "numberOfConfirmations"
    val HEIGHT_PARAMETER = "height"
    val DECRYPTED_MESSAGE_IS_TEXT_PARAMETER = "decryptedMessageIsText"
    val REFUND_NQT_PARAMETER = "refundNQT"
    val DATA_PARAMETER = "data"
    val NONCE_PARAMETER = "nonce"
    val SUBSCRIPTION_PARAMETER = "subscription"
    val ALIAS_URI_PARAMETER = "aliasURI"
    val NAME_PARAMETER = "name"
    val DESCRIPTION_PARAMETER = "description"
    val FREQUENCY_PARAMETER = "frequency"
    val AT_PARAMETER = "at"
    val CREATION_BYTES_PARAMETER = "creationBytes"
    val HEX_STRING_PARAMETER = "hexString"
    val TRANSACTION_BYTES_PARAMETER = "transactionBytes"
    val TRANSACTION_JSON_PARAMETER = "transactionJSON"
    val CODE_PARAMETER = "code"
    val DPAGES_PARAMETER = "dpages"
    val CSPAGES_PARAMETER = "cspages"
    val USPAGES_PARAMETER = "uspages"
    val MIN_ACTIVATION_AMOUNT_NQT_PARAMETER = "minActivationAmountNQT"
    val DISCOUNT_NQT_PARAMETER = "discountNQT"
    val GOODS_TO_ENCRYPT_PARAMETER = "goodsToEncrypt"
    val GOODS_IS_TEXT_PARAMETER = "goodsIsText"
    val TAGS_PARAMETER = "tags"
    val DELIVERY_DEADLINE_TIMESTAMP_PARAMETER = "deliveryDeadlineTimestamp"
    val DELTA_QUANTITY_PARAMETER = "deltaQuantity"
    val ESCROW_PARAMETER = "escrow"
    val DECISION_PARAMETER = "decision"
    val DECIMALS_PARAMETER = "decimals"
    val PERIOD_PARAMETER = "period"
    val ESCROW_DEADLINE_PARAMETER = "escrowDeadline"
    val DEADLINE_ACTION_PARAMETER = "deadlineAction"
    val REQUIRED_SIGNERS_PARAMETER = "requiredSigners"
    val SIGNERS_PARAMETER = "signers"
    val INCLUDE_ASSET_INFO_PARAMETER = "includeAssetInfo"
    val INCLUDE_TRANSACTIONS_PARAMETER = "includeTransactions"
    val TYPE_PARAMETER = "type"
    val SUBTYPE_PARAMETER = "subtype"
    val UNSIGNED_TRANSACTION_BYTES_PARAMETER = "unsignedTransactionBytes"
    val SIGNATURE_HASH_PARAMETER = "signatureHash"
    val FULL_HASH_RESPONSE = "fullHash"
    val TRANSACTION_PARAMETER = "transaction"
    val FULL_HASH_PARAMETER = "fullHash"
    val ACCOUNT_ID_PARAMETER = "accountId"
    val NUM_BLOCKS_PARAMETER = "numBlocks"
    val BLOCK_PARAMETER = "block"
    val INCLUDE_COUNTS_PARAMETER = "includeCounts"
    val DEADLINE_PARAMETER = "deadline"
    val REFERENCED_TRANSACTION_FULL_HASH_PARAMETER = "referencedTransactionFullHash"
    val REFERENCED_TRANSACTION_PARAMETER = "referencedTransaction"
    val BROADCAST_PARAMETER = "broadcast"
    val RECIPIENT_PUBLIC_KEY_PARAMETER = "recipientPublicKey"
    val COMMENT_PARAMETER = "comment"
    val MESSAGE_IS_TEXT_PARAMETER = "messageIsText"
    val MESSAGE_PARAMETER = "message"
    val UNSIGNED_TRANSACTION_JSON_PARAMETER = "unsignedTransactionJSON"
    val AMOUNT_BURST_PARAMETER = "amountNXT"
    val FEE_BURST_PARAMETER = "feeNXT"
    val IN_STOCK_ONLY_PARAMETER = "inStockOnly"
    val COMPLETED_PARAMETER = "completed"
    val PEER_PARAMETER = "peer"
    val ACTIVE_PARAMETER = "active"
    val STATE_PARAMETER = "state"
    val ID_PARAMETER = "id"
    val URI_PARAMETER = "uri"
    val FEE_PARAMETER = "fee"
    val TOKEN_PARAMETER = "token"
    val WEBSITE_PARAMETER = "website"
    val AMOUNT_PARAMETER = "amount"
    val PRICE_PARAMETER = "price"
    val HOST_PARAMETER = "host"
    val DATE_PARAMETER = "date"
    val ESCROW_ID_PARAMETER = "escrowId"
    val SUBSCRIPTION_ID_PARAMETER = "subscriptionId"
    val BLOCK_HEIGHT_PARAMETER = "blockheight"
    val SUBSCRIPTIONS_RESPONSE = "subscriptions"
    val ESCROWS_RESPONSE = "escrows"
    val ACCOUNTS_RESPONSE = "accounts"
    val RECIPIENTS_RESPONSE = "recipients"
    val LAST_UNCONFIRMED_TRANSACTION_TIMESTAMP_PARAMETER = "lastUnconfirmedTransactionTimestamp"
    val LIMIT_UNCONFIRMED_TRANSACTIONS_RETRIEVED_PARAMETER = "limitUnconfirmedTransactionsRetrieved"
    val RECEIVER_ID_PARAMETER = "receiverId"
    val FEE_SUGGESTION_TYPE_PARAMETER = "feeSuggestionType"
    val IMMUTABLE_PARAMETER = "immutable"
    val FEE_SUGGESTION_RESPONSE = "feeSuggestion"
    val INCLUDE_INDIRECT_PARAMETER = "includeIndirect"

    fun isFalse(text: String): Boolean {
        return "false".equals(text, ignoreCase = true)
    }

    fun isTrue(text: String): Boolean {
        return "true".equals(text, ignoreCase = true)
    }

    fun isZero(recipientValue: String): Boolean {
        return "0" == recipientValue
    }
}
