// Kept because of JDBC flyway migration V7_3 - see src.brs.db.sql.migration

create table "account_balance"
(
  "db_id"               BIGINT generated by default as identity
    primary key,
  "id"                  BIGINT               not null,
  "balance"             BIGINT               not null,
  "unconfirmed_balance" BIGINT               not null,
  "forged_balance"      BIGINT               not null,
  "height"              INTEGER              not null,
  "latest"              BOOLEAN default TRUE not null
);

create index "account_balance_height_idx"
  on "account_balance" ("height");

create unique hash index "account_balance_id_height_idx"
  on "account_balance" ("id", "height");

create index "account_balance_id_latest_idx"
  on "account_balance" ("id", "latest");
